# Contributor: @DLC01
TERMUX_PKG_HOMEPAGE=https://gitlab.com/ecodis/exhale
TERMUX_PKG_DESCRIPTION="Open source xHE-AAC encoder"
TERMUX_PKG_LICENSE="custom"
TERMUX_PKG_LICENSE_FILE="include/License.htm"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.2.2+r2"
TERMUX_PKG_SRCURL="https://gitlab.com/ecodis/exhale/-/archive/c33cf75b002806ca41e7a1c0deadfcf622cbd786/exhale-c33cf75b002806ca41e7a1c0deadfcf622cbd786.tar.gz"
TERMUX_PKG_SHA256=SKIP_CHECKSUM
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="libc++"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="-DBUILD_SHARED_LIBS=ON"
